name: RTSP AI Inference CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: rtsp-ai-inference

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      # Hard errors only
      - name: flake8 (errors only)
        run: flake8 app.py --select=E9,F63,F7,F82 --show-source --statistics
      # Full report, non-blocking (simple & clean)
      - name: flake8 (full, non-blocking)
        run: flake8 app.py --exit-zero --max-line-length=100 --statistics

  build-and-push:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (only on main)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          BRANCH_TAG=${GITHUB_REF_NAME//\//-}
          echo "sha_tag=${SHA_TAG}" >> $GITHUB_OUTPUT
          echo "branch_tag=${BRANCH_TAG}" >> $GITHUB_OUTPUT
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo "latest=true" >> $GITHUB_OUTPUT
          else
            echo "latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Build (push only on main)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.branch_tag }}
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}
            ${{ steps.meta.outputs.latest == 'true' && format('{0}/{1}/{2}:latest', env.REGISTRY, secrets.DOCKERHUB_USERNAME, env.IMAGE_NAME) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  simulate-deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull latest image
        run: docker pull ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      # IMPORTANT: Runner pe camera nahi hota, isliye yeh device-independent sanity check hai.
      - name: Ephemeral health-check (device-independent)
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            python - <<'PY'
          import cv2, sys
          c = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
          print("Cascade OK:", not c.empty())
          sys.exit(0 if not c.empty() else 1)
          PY

